package org.ifaco.migratio;

@SuppressWarnings({"unused", "RedundantSuppression"})
public final class Countries {
    public static final String[] EN = new String[]{
            "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
            "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
            "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia",
            "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso",
            "Burundi", "Côte d'Ivoire", "Cabo Verde", "Cambodia", "Cameroon", "Canada",
            "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros",
            "Congo-Brazzaville", "Costa Rica", "Croatia", "Cuba", "Cyprus",
            "Czech Republic", "Democratic Republic of Congo", "Denmark", "Djibouti",
            "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
            "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
            "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
            "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
            "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq",
            "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya",
            "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho",
            "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi",
            "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius",
            "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco",
            "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
            "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia",
            "Norway", "Oman", "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea",
            "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia",
            "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
            "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
            "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
            "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan",
            "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania",
            "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
            "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
            "United Kingdom", "United States of America", "Uruguay", "Uzbekistan", "Vanuatu",
            "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
    };
    public static final String[] FA = new String[]{
            "افغانستان", "آلبانی", "الجزایر", "آندورا", "آنگولا", "آنتیگوا و باربودا", "آرژانتین", "ارمنستان", "استرالیا", "اتریش", "آذربایجان",
            "باهاما", "بحرین", "بنگلادش", "باربادوس", "بلاروس", "بلژیک", "بلیز", "بنین", "بوتان", "بولیوی", "بوسنی و هرزگوین",
            "بوتسوانا", "برزیل", "برونئی", "بلغارستان", "بورکینافاسو", "بوروندی", "ساحل عاج", "کابو ورد", "کامبوج", "کامرون",
            "کانادا", "جمهوری آفریقای مرکزی", "چاد", "شیلی", "چین", "کلمبیا", "کومور", "کنگو", "کاستاریکا", "کرواسی", "کوبا",
            "قبرس", "جمهوری چک", "جمهوری دموکراتیک کنگو", "دانمارک", "جیبوتی", "دومینیکا", "جمهوری دومینیکن", "اکوادور",
            "مصر", "السالوادور", "گینه استوایی", "اریتره", "استونی", "اسواتینی", "اتیوپی", "فیجی", "فنلاند",
            "فرانسه", "گابن", "گامبیا", "گرجستان", "آلمان", "غنا", "یونان", "گرنادا", "گواتمالا", "گینه", "گینه بیسائو", "گویان",
            "هائیتی", "سریر مقدس (واتیکان)", "هندوراس", "مجارستان", "ایسلند", "هند", "اندونزی", "ایران", "عراق", "ایرلند",
            "اسرائیل", "ایتالیا", "جامائیکا", "ژاپن", "اردن", "قزاقستان", "کنیا", "کیریباتی", "کوزوو", "کویت", "قرقیزستان", "لائوس",
            "لتونی", "لبنان", "لسوتو", "لیبریا", "لیبی", "لیختنشتاین", "لیتوانی", "لوگزامبورگ", "ماداگاسکار", "مالاوی", "مالزی",
            "مالدیو", "مالی", "مالت", "جزایر مارشال", "موریتانی", "موریس", "مکزیک", "میکرونزی", "مولداوی", "موناکو", "مغولستان",
            "مونته نگرو", "مراکش", "کوزامبیک", "میانمار", "نامیبیا", "نائورو", "نپال", "هلند", "نیوزیلند", "نیکاراگوئه", "نیجر",
            "نیجریه", "کره شمالی", "مقدونیه شمالی", "نروژ", "عمان", "پاکستان", "پالائو", "فلسطین", "پاناما", "پاپوا گینه نو",
            "پاراگوئه", "پرو", "فیلیپین", "لهستان", "پرتغال", "قطر", "رومانی", "روسیه", "رواندا", "سنت کیتس و نوویس",
            "سنت لوسیا", "سنت وینسنت و گرنادینها", "ساموآ", "سان مارینو", "سائو تومه و پرینسیپ", "عربستان سعودی", "سنگال",
            "صربستان", "سیشل", "سیرا لئون", "سنگاپور", "اسلواکی", "اسلوونی", "جزایر سلیمان", "سومالی", "آفریقای جنوبی",
            "کره جنوبی", "سودان جنوبی", "اسپانیا", "سری لانکا", "سودان", "سورینام", "سوئد", "سوئیس", "سوریه", "تایوان",
            "تاجیکستان", "تانزانیا", "تایلند", "تیمور-لست", "توگو", "تونگا", "ترینیداد و توباگو", "تونس", "ترکیه", "ترکمنستان",
            "تووالو", "اوگاندا", "اوکراین", "امارات متحده عربی", "بریتانیا", "ایالات متحده امریکا", "اوروگوئه", "ازبکستان", "واناتو",
            "ونزوئلا", "ویتنام", "یمن", "زامبیا", "زیمبابوه"
    };
    public static final String[] AR = new String[]{
            "أفغانستان", "ألبانيا", "الجزائر", "أندورا", "أنغولا", "أنتيغوا وبربودا", "الأرجنتين", "أرمينيا", "أستراليا",
            "النمسا", "أذربيجان", "جزر البهاما", "البحرين", "بنغلاديش", "بربادوس", "روسيا البيضاء", "بلجيكا", "بليز",
            "بنين", "بوتان", "بوليفيا", "البوسنة والهرسك", "بوتسوانا", "البرازيل", "بروناي", "بلغاريا", "بوركينا فاسو",
            "بوروندي", "ساحل العاج", "كابو فيردي", "كمبوديا", "الكاميرون", "كندا", "جمهورية افريقيا الوسطى", "تشاد",
            "تشيلي", "الصين", "كولومبيا", "جزر القمر", "الكونغو برازافيل", "كوستا ريكا", "كرواتيا", "كوبا",
            "قبرص", "التشيك", "جمهورية الكونغو الديمقراطية", "الدنمارك", "جيبوتي", "دومينيكا",
            "جمهورية الدومنيكان", "إكوادور", "مصر", "السلفادور", "غينيا الإستوائية", "إريتريا", "إستونيا",
            "إيسواتيني", "أثيوبيا", "فيجي", "فنلندا", "فرنسا", "الغابون", "غامبيا", "جورجيا",
            "ألمانيا", "غانا", "اليونان", "غرينادا", "غواتيمالا", "غينيا", "غينيا - بيساو", "غيانا", "هايتي",
            "الكرسي الرسولي", "هندوراس", "هنغاريا", "أيسلندا", "الهند", "إندونيسيا", "إيران", "العراق", "أيرلندا",
            "إسرائيل", "إيطاليا", "جامايكا", "اليابان", "الأردن", "كازاخستان", "كينيا", "كيريباتي", "كوسوفو", "الكويت",
            "قيرغيزستان", "لاوس", "لاتفيا", "لبنان", "ليسوتو", "ليبيريا", "ليبيا", "ليختنشتاين", "ليتوانيا",
            "لوكسمبورج", "مدغشقر", "ملاوي", "ماليزيا", "جزر المالديف", "مالي", "مالطا", "جزر مارشال", "موريتانيا",
            "موريشيوس", "المكسيك", "ميكرونيزيا", "مولدوفا", "موناكو", "منغوليا", "منغوليا", "المغرب", "موزمبيق",
            "ميانمار", "ناميبيا", "ناورو", "نيبال", "هولندا", "نيوزيلندا", "نيكاراغوا", "النيجر",
            "نيجيريا", "كوريا الشمالية", "مقدونيا الشمالية", "النرويج", "سلطنة عمان", "باكستان", "بالاو",
            "دولة فلسطين", "بنما", "بابوا غينيا الجديدة", "باراغواي", "بيرو", "الفلبين", "بولندا", "البرتغال",
            "دولة قطر", "رومانيا", "روسيا", "رواندا", "سانت كيتس ونيفيس", "القديسة لوسيا",
            "سانت فنسنت وجزر غرينادين", "ساموا", "سان مارينو", "سان تومي وبرينسيبي", "المملكة العربية السعودية",
            "السنغال", "صربيا", "سيشيل", "سيرا ليون", "سنغافورة", "سلوفاكيا", "سلوفينيا", "جزر سليمان",
            "الصومال", "جنوب أفريقيا", "كوريا الجنوبية", "جنوب السودان", "إسبانيا", "سيريلانكا", "السودان", "سورينام",
            "السويد", "سويسرا", "سوريا", "تايوان", "طاجيكستان", "تنزانيا", "تايلاند", "تيمور ليشتي", "توجو",
            "تونغا", "ترينداد وتوباغو", "تونس", "تركيا", "تركمانستان", "توفالو", "أوغندا", "أوكرانيا",
            "الإمارات العربية المتحدة", "المملكة المتحدة", "الولايات المتحدة الامريكية", "أوروغواي", "أوزبكستان", "فانواتو",
            "فنزويلا", "فيتنام", "اليمن", "زامبيا", "زيمبابوي"
    };
    public static final String[] DE = new String[]{
            "Afghanistan", "Albanien", "Algerien", "Andorra", "Angola", "Antigua und Barbuda",
            "Argentinien", "Armenien", "Australien", "Österreich", "Aserbaidschan", "Bahamas",
            "Bahrain", "Bangladesch", "Barbados", "Weißrussland", "Belgien", "Belize", "Benin",
            "Bhutan", "Bolivien", "Bosnien und Herzegowina", "Botswana", "Brasilien", "Brunei",
            "Bulgarien", "Burkina Faso", "Burundi", "Elfenbeinküste", "Cabo Verde", "Kambodscha",
            "Kamerun", "Kanada", "Zentralafrikanische Republik", "Tschad", "Chile", "China",
            "Kolumbien", "Komoren", "Kongo-Brazzaville", "Costa Rica", "Kroatien", "Kuba",
            "Zypern", "Tschechien", "Demokratische Republik Kongo",
            "Dänemark", "Dschibuti", "Dominica", "Dominikanische Republik", "Ecuador", "Ägypten",
            "El Salvador", "Äquatorialguinea", "Eritrea", "Estland",
            "Eswatini", "Äthiopien", "Fidschi", "Finnland", "Frankreich",
            "Gabun", "Gambia", "Georgia", "Deutschland", "Ghana", "Griechenland", "Grenada",
            "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heiliger Stuhl",
            "Honduras", "Ungarn", "Island", "Indien", "Indonesien", "Iran", "Irak", "Irland",
            "Israel", "Italien", "Jamaika", "Japan", "Jordan", "Kasachstan", "Kenia", "Kiribati",
            "Kosovo", "Kuwait", "Kirgisistan", "Laos", "Lettland", "Libanon", "Lesotho", "Liberia",
            "Libyen", "Liechtenstein", "Litauen", "Luxemburg", "Madagaskar", "Malawi", "Malaysia",
            "Malediven", "Mali", "Malta", "Marshallinseln", "Mauretanien", "Mauritius", "Mexiko",
            "Mikronesien", "Moldawien", "Monaco", "Mongolei", "Montenegro", "Marokko", "Mosambik",
            "Myanmar", "Namibia", "Nauru", "Nepal", "Niederlande", "Neuseeland",
            "Nicaragua", "Niger", "Nigeria", "Nord Korea", "Nordmakedonien", "Norwegen", "Oman",
            "Pakistan", "Palau", "Palästina-Staat", "Panama", "Papua Neu-Guinea", "Paraguay",
            "Peru", "Philippinen", "Polen", "Portugal", "Katar", "Rumänien", "Russland", "Ruanda",
            "St. Kitts und Nevis", "St. Lucia", "St. Vincent und die Grenadinen", "Samoa",
            "San Marino", "Sao Tome und Principe", "Saudi Arabien", "Senegal", "Serbien",
            "Seychellen", "Sierra Leone", "Singapur", "Slowakei", "Slowenien", "Salomon-Inseln",
            "Somalia", "Südafrika", "Südkorea", "Südsudan", "Spanien", "Sri Lanka", "Sudan",
            "Suriname", "Schweden", "Schweiz", "Syrien", "Taiwan", "Tadschikistan", "Tansania",
            "Thailand", "Timor-Leste", "Gehen", "Tonga", "Trinidad und Tobago", "Tunesien",
            "Turquie", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine",
            "Vereinigte Arabische Emirate", "Großbritannien", "vereinigte Staaten von Amerika",
            "Uruguay", "Usbekistan", "Vanuatu", "Venezuela", "Vietnam", "Jemen", "Sambia",
            "Zimbabwe"
    };
    public static final String[] FR = new String[]{
            "Afghanistan", "Albanie", "Algérie", "Andorre", "Angola", "Antigua-et-Barbuda",
            "Argentine", "Arménie", "Australie", "Autriche", "Azerbaïdjan", "Bahamas", "Bahrein",
            "Bangladesh", "Barbade", "Biélorussie", "Belgique", "Belize", "Bénin", "Bhoutan",
            "Bolivie", "Bosnie Herzégovine", "Botswana", "Brésil", "Brunei", "Bulgarie",
            "Burkina Faso", "Burundi", "Côte d'Ivoire", "Cabo Verde", "Cambodge", "Cameroun",
            "Canada", "République centrafricaine", "Tchad", "Chili", "Chine", "Colombie",
            "Comores", "Congo-Brazzaville", "Costa Rica", "Croatie", "Cuba", "Chypre",
            "Tchéquie", "République Démocratique du Congo", "Danemark",
            "Djibouti", "Dominique", "République Dominicaine", "Équateur", "Egypte", "Le Salvador",
            "Guinée Équatoriale", "Érythrée", "Estonie", "Eswatini",
            "Ethiopie", "Fidji", "Finlande", "France", "Gabon", "Gambia", "Géorgie", "Allemagne",
            "Ghana", "Grèce", "Grenade", "Guatemala", "Guinée", "Guinée-Bissau", "Guyane", "Haïti",
            "Saint-Siège", "Honduras", "Hongrie", "Islande", "Inde", "Indonésie", "Iran", "Irak",
            "Irlande", "Israël", "Italie", "Jamaïque", "Japon", "Jordan", "Kazakhstan", "Kenya",
            "Kiribati", "Kosovo", "Koweit", "Kirghizistan", "Laos", "Lettonie", "Liban", "Lesotho",
            "Libéria", "Libye", "Liechtenstein", "Lituanie", "Luxembourg", "Madagascar", "Malawi",
            "Malaisie", "Maldives", "Mali", "Malte", "Iles Marshall", "Mauritanie", "Maurice",
            "Mexique", "Micronésie", "Moldova", "Monaco", "Mongolie", "Monténégro", "Maroc",
            "Mozambique", "Myanmar", "Namibie", "Nauru", "Népal",
            "Pays-Bas", "Nouvelle-Zélande", "Nicaragua", "Niger", "Nigeria", "Corée du Nord",
            "Macédoine du Nord", "Norvège", "Oman", "Pakistan", "Palau", "État de Palestine",
            "Panama", "Papouasie Nouvelle Guinée", "Paraguay", "Pérou", "Philippines", "Pologne",
            "Portugal", "Qatar", "Roumanie", "Russie", "Rwanda", "Saint-Christophe-et-Niévès",
            "Sainte-Lucie", "Saint-Vincent-et-les-Grenadines", "Samoa", "Saint Marin",
            "Sao Tomé et Principe", "Arabie Saoudite", "Sénégal", "Serbie", "Seychelles",
            "Sierra Leone", "Singapour", "Slovaquie", "Slovénie", "Les îles Salomon", "Somalie",
            "Afrique du Sud", "Corée du Sud", "Soudan du sud", "Espagne", "Sri Lanka", "Soudan",
            "Suriname", "Suède", "Suisse", "Syrie", "Taïwan", "Tadjikistan", "Tanzanie",
            "Thaïlande", "Timor-Leste", "Aller", "Tonga", "Trinité-et-Tobago", "Tunisie", "Türkei",
            "Turkménistan", "Tuvalu", "Ouganda", "Ukraine", "Emirats Arabes Unis", "Royaume-Uni",
            "États-Unis d'Amérique", "Uruguay", "Ouzbékistan", "Vanuatu", "Venezuela", "Vietnam",
            "Yémen", "Zambie", "Zimbabwe"
    };

    public static final String[] TAGS = new String[]{
            "afghan", "alba", "alger", "andor", "angol", "antigbar", "argen", "armen", "austra",
            "austri", "azer", "baham", "bahr", "bangla", "barba", "belar", "belg", "beliz",
            "benin", "bhut", "boliv", "bosni", "botsw", "braz", "brun", "bulgar", "burkfa",
            "burund", "ivorcoast", "cabover", "cambod", "camer", "can", "car", "chad", "chil",
            "china", "colom", "comor", "congo", "costar", "croat", "cuba", "cypr", "czech", "drc",
            "denm", "djib", "dominic", "dominicrep", "ecuad", "egypt", "elsalv", "eqguin", "erit",
            "est", "eswat", "ethiop", "fiji", "fin", "franc", "gabon", "gamb", "georg", "german",
            "ghana", "greec", "grenad", "guatem", "guinea", "guineabiss", "guyana", "haiti",
            "holsee", "hondur", "hungar", "ice", "ind", "indones", "iran", "iraq", "ire", "heb",
            "ital", "jamaic", "jpn", "jord", "kazakh", "kenya", "kiribas", "kos", "kuwait",
            "kyrgyz", "lao", "latvia", "leban", "lesoth", "liber", "liby", "liechtens", "lithua",
            "luxem", "madagas", "malaw", "malay", "maldav", "mali", "malt", "marshal", "mauritan",
            "mauritius", "mexic", "micrones", "moldov", "monaco", "mongol", "montenegr", "moroc",
            "mozam", "myanm", "namibia", "nauru", "nepal", "nether", "newz", "nicarag", "niger",
            "nigeria", "nkorea", "nmacedon", "norw", "oman", "pak", "palau", "palestin", "panam",
            "papuang", "paragu", "peru", "philip", "pol", "port", "qtr", "roman", "rus", "rwand",
            "sankitts", "sanluc", "sanvinc", "samoa", "sanmar", "saotome", "arabia", "senegal",
            "serb", "seychel", "sierra", "singap", "slovak", "sloven", "solomon", "somali",
            "southafr", "skorea", "ssudan", "spain", "srilanka", "sudan", "surinam", "swed",
            "swiss", "syria", "tai", "tajik", "tanzan", "thai", "timorlest", "togo", "tong",
            "trinidatob", "tunis", "turk", "turkmen", "tuval", "ugand", "ukrain", "uae", "uk",
            "usa", "urug", "uzbek", "vanua", "venez", "viet", "ymn", "zamb", "zimbab"
    };
}
